#pragma once
#include <stdint.h>

#define UARTVC_START_BYTE 0x7E
#define UARTVC_ESCAPE_BYTE 0x7D
#define UARTVC_XOR_BYTE 0x20

#define UARTVC_MAX_PAYLOAD 64
#define UARTVC_MAX_FRAME (1 + 1 + 1 + UARTVC_MAX_PAYLOAD + 1)

#define UARTVC_FLAG_ACK_REQ 0x80
#define UARTVC_FLAG_ACK_PKT 0x40
#define UARTVC_FLAG_FIN 0x20
#define UARTVC_CHANNEL_MASK 0X0F

#define UARTVC_MAX_CHANNELS 16

#define UARTVC_ACK_TIMEOUT_MS 100
#define UARTVC_MAX_RETRIES 3

#define UARTVC_REASSEMBLY_TIMEOUT_MS 100
#define UARTVC_MAX_REASSEMBLY_BUFFER 512
